# 
# GNU Sparky --- A 5v5 character-based libre tactical shooter
# Copyright (C) 2024 Wasym A. Alonso
# 
# This file is part of Sparky.
# 
# Sparky is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Sparky is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Sparky.  If not, see <http://www.gnu.org/licenses/>.
# 


#+AUTHOR: Wasym A. Alonso
#+TITLE: How to contribute?

Thank you for your interest in contributing to this project, it is extremely appreciated.

* Submitting changes

Please, send a GitHub Pull Request (PR) to [[https://github.com/sparky-game/sparky][sparky-game/sparky]] with a clear list of what you've done ([[http://help.github.com/pull-requests/][read more about PRs]]). The best place to start is to fork the repository to your personal profile, and start working from there.

Please, follow our coding conventions below and make sure all of your commits are atomic (one feature per commit) and have descriptive messages and an optional description (if needed). One-line messages are fine for small changes, but bigger changes should look like this:

#+begin_src shell
git commit -s -m "Commit subject
>
> A paragraph describing what changed and its impact."
#+end_src

* Coding conventions

Start reading our code and you'll get the hang of it. We optimize for readabillity, but not compromising on its looks:

- We indent using two spaces (soft tabs)
- We ALWAYS put spaces after list items and method parameters (~[1, 2, 3]~, not ~[1,2,3]~) and around operators (~x += 1~, not ~x+=1~)
- This is free and open source software. Consider the people who will read your code, and make it look nice for them. It's sort of like driving a car: perhaps you love doing donuts when you're alone, but with passengers the goal is to make the ride as smooth as possible.

For more information, see [[https://github.com/sparky-game/sparky/blob/master/CODE_OF_CONDUCT.md][CODE_OF_CONDUCT.md]].

Thanks a lot. Yours faithfully,

Wasym A. Alonso
