name: Bug Report
description: Report a bug
labels: ['🐛 bug']
body:
  - type: markdown
    attributes:
      value: Please fill out the sections below to help everyone identify and fix the bug.
  - type: textarea
    id: description
    attributes:
      label: Describe your issue
      placeholder: When I do this it happens that ...
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Do this ...
        2. Do that ...
        3. Wait few seconds ...
        ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What was the expected result?
      placeholder: I expected this to happen ...
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Put here any screenshots or videos (optional)
  - type: markdown
    attributes:
      value: Thanks for reporting this issue! We will get back to you as soon as possible.
